sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t marcobeyer/german-syntaxnet-docker .

script:
  - echo 'container built'

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push marcobeyer/german-syntaxnet-docker;
    fi
